#
# ! THIS IS THE FORMAT FOR KEYS.PY FILE
# ! YOU CAN GET YOUR KEYS BY MAKING AN APP USING TWITTER DEVELOPER'S ACCOUNT
# ! MAKE YOUR OWN KEYS.PY FILE BASED ON THIS FORMAT
#

CONSUMER_KEY = 'your-api-key'
CONSUMER_SECRET = 'your-api-secret-key'
ACCESS_KEY = 'your-access-token'
ACCESS_SECRET = 'your-access-token-secret'
